# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/madeley/Documents/examples/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/madeley/Documents/examples/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/madeley/Documents/examples/project/CMakeFiles /Users/madeley/Documents/examples/project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/madeley/Documents/examples/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project_bin

# Build rule for target.
project_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project_bin
.PHONY : project_bin

# fast build rule for target.
project_bin/fast:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/build
.PHONY : project_bin/fast

#=============================================================================
# Target rules for targets named igl_viewer

# Build rule for target.
igl_viewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 igl_viewer
.PHONY : igl_viewer

# fast build rule for target.
igl_viewer/fast:
	$(MAKE) -f libigl/CMakeFiles/igl_viewer.dir/build.make libigl/CMakeFiles/igl_viewer.dir/build
.PHONY : igl_viewer/fast

#=============================================================================
# Target rules for targets named igl_opengl_glfw

# Build rule for target.
igl_opengl_glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 igl_opengl_glfw
.PHONY : igl_opengl_glfw

# fast build rule for target.
igl_opengl_glfw/fast:
	$(MAKE) -f libigl/CMakeFiles/igl_opengl_glfw.dir/build.make libigl/CMakeFiles/igl_opengl_glfw.dir/build
.PHONY : igl_opengl_glfw/fast

#=============================================================================
# Target rules for targets named igl_opengl2

# Build rule for target.
igl_opengl2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 igl_opengl2
.PHONY : igl_opengl2

# fast build rule for target.
igl_opengl2/fast:
	$(MAKE) -f libigl/CMakeFiles/igl_opengl2.dir/build.make libigl/CMakeFiles/igl_opengl2.dir/build
.PHONY : igl_opengl2/fast

#=============================================================================
# Target rules for targets named igl_opengl

# Build rule for target.
igl_opengl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 igl_opengl
.PHONY : igl_opengl

# fast build rule for target.
igl_opengl/fast:
	$(MAKE) -f libigl/CMakeFiles/igl_opengl.dir/build.make libigl/CMakeFiles/igl_opengl.dir/build
.PHONY : igl_opengl/fast

#=============================================================================
# Target rules for targets named igl

# Build rule for target.
igl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 igl
.PHONY : igl

# fast build rule for target.
igl/fast:
	$(MAKE) -f libigl/CMakeFiles/igl.dir/build.make libigl/CMakeFiles/igl.dir/build
.PHONY : igl/fast

#=============================================================================
# Target rules for targets named nanogui

# Build rule for target.
nanogui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nanogui
.PHONY : nanogui

# fast build rule for target.
nanogui/fast:
	$(MAKE) -f libigl/nanogui/CMakeFiles/nanogui.dir/build.make libigl/nanogui/CMakeFiles/nanogui.dir/build
.PHONY : nanogui/fast

#=============================================================================
# Target rules for targets named nanogui-obj

# Build rule for target.
nanogui-obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nanogui-obj
.PHONY : nanogui-obj

# fast build rule for target.
nanogui-obj/fast:
	$(MAKE) -f libigl/nanogui/CMakeFiles/nanogui-obj.dir/build.make libigl/nanogui/CMakeFiles/nanogui-obj.dir/build
.PHONY : nanogui-obj/fast

#=============================================================================
# Target rules for targets named glfw_objects

# Build rule for target.
glfw_objects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw_objects
.PHONY : glfw_objects

# fast build rule for target.
glfw_objects/fast:
	$(MAKE) -f libigl/nanogui/ext_build/glfw/src/CMakeFiles/glfw_objects.dir/build.make libigl/nanogui/ext_build/glfw/src/CMakeFiles/glfw_objects.dir/build
.PHONY : glfw_objects/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f libigl/nanogui/ext_build/glfw/src/CMakeFiles/glfw.dir/build.make libigl/nanogui/ext_build/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

Detector/HarrisDetector.o: Detector/HarrisDetector.cpp.o

.PHONY : Detector/HarrisDetector.o

# target to build an object file
Detector/HarrisDetector.cpp.o:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/Detector/HarrisDetector.cpp.o
.PHONY : Detector/HarrisDetector.cpp.o

Detector/HarrisDetector.i: Detector/HarrisDetector.cpp.i

.PHONY : Detector/HarrisDetector.i

# target to preprocess a source file
Detector/HarrisDetector.cpp.i:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/Detector/HarrisDetector.cpp.i
.PHONY : Detector/HarrisDetector.cpp.i

Detector/HarrisDetector.s: Detector/HarrisDetector.cpp.s

.PHONY : Detector/HarrisDetector.s

# target to generate assembly for a file
Detector/HarrisDetector.cpp.s:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/Detector/HarrisDetector.cpp.s
.PHONY : Detector/HarrisDetector.cpp.s

Detector/Mesh.o: Detector/Mesh.cpp.o

.PHONY : Detector/Mesh.o

# target to build an object file
Detector/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/Detector/Mesh.cpp.o
.PHONY : Detector/Mesh.cpp.o

Detector/Mesh.i: Detector/Mesh.cpp.i

.PHONY : Detector/Mesh.i

# target to preprocess a source file
Detector/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/Detector/Mesh.cpp.i
.PHONY : Detector/Mesh.cpp.i

Detector/Mesh.s: Detector/Mesh.cpp.s

.PHONY : Detector/Mesh.s

# target to generate assembly for a file
Detector/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/Detector/Mesh.cpp.s
.PHONY : Detector/Mesh.cpp.s

Detector/Vertex.o: Detector/Vertex.cpp.o

.PHONY : Detector/Vertex.o

# target to build an object file
Detector/Vertex.cpp.o:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/Detector/Vertex.cpp.o
.PHONY : Detector/Vertex.cpp.o

Detector/Vertex.i: Detector/Vertex.cpp.i

.PHONY : Detector/Vertex.i

# target to preprocess a source file
Detector/Vertex.cpp.i:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/Detector/Vertex.cpp.i
.PHONY : Detector/Vertex.cpp.i

Detector/Vertex.s: Detector/Vertex.cpp.s

.PHONY : Detector/Vertex.s

# target to generate assembly for a file
Detector/Vertex.cpp.s:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/Detector/Vertex.cpp.s
.PHONY : Detector/Vertex.cpp.s

src/Process.o: src/Process.cpp.o

.PHONY : src/Process.o

# target to build an object file
src/Process.cpp.o:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/Process.cpp.o
.PHONY : src/Process.cpp.o

src/Process.i: src/Process.cpp.i

.PHONY : src/Process.i

# target to preprocess a source file
src/Process.cpp.i:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/Process.cpp.i
.PHONY : src/Process.cpp.i

src/Process.s: src/Process.cpp.s

.PHONY : src/Process.s

# target to generate assembly for a file
src/Process.cpp.s:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/Process.cpp.s
.PHONY : src/Process.cpp.s

src/funcgui.o: src/funcgui.cpp.o

.PHONY : src/funcgui.o

# target to build an object file
src/funcgui.cpp.o:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/funcgui.cpp.o
.PHONY : src/funcgui.cpp.o

src/funcgui.i: src/funcgui.cpp.i

.PHONY : src/funcgui.i

# target to preprocess a source file
src/funcgui.cpp.i:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/funcgui.cpp.i
.PHONY : src/funcgui.cpp.i

src/funcgui.s: src/funcgui.cpp.s

.PHONY : src/funcgui.s

# target to generate assembly for a file
src/funcgui.cpp.s:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/funcgui.cpp.s
.PHONY : src/funcgui.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/myDisplay.o: src/myDisplay.cpp.o

.PHONY : src/myDisplay.o

# target to build an object file
src/myDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/myDisplay.cpp.o
.PHONY : src/myDisplay.cpp.o

src/myDisplay.i: src/myDisplay.cpp.i

.PHONY : src/myDisplay.i

# target to preprocess a source file
src/myDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/myDisplay.cpp.i
.PHONY : src/myDisplay.cpp.i

src/myDisplay.s: src/myDisplay.cpp.s

.PHONY : src/myDisplay.s

# target to generate assembly for a file
src/myDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/myDisplay.cpp.s
.PHONY : src/myDisplay.cpp.s

src/mySkeleton.o: src/mySkeleton.cpp.o

.PHONY : src/mySkeleton.o

# target to build an object file
src/mySkeleton.cpp.o:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/mySkeleton.cpp.o
.PHONY : src/mySkeleton.cpp.o

src/mySkeleton.i: src/mySkeleton.cpp.i

.PHONY : src/mySkeleton.i

# target to preprocess a source file
src/mySkeleton.cpp.i:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/mySkeleton.cpp.i
.PHONY : src/mySkeleton.cpp.i

src/mySkeleton.s: src/mySkeleton.cpp.s

.PHONY : src/mySkeleton.s

# target to generate assembly for a file
src/mySkeleton.cpp.s:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/mySkeleton.cpp.s
.PHONY : src/mySkeleton.cpp.s

src/remesh.o: src/remesh.cpp.o

.PHONY : src/remesh.o

# target to build an object file
src/remesh.cpp.o:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/remesh.cpp.o
.PHONY : src/remesh.cpp.o

src/remesh.i: src/remesh.cpp.i

.PHONY : src/remesh.i

# target to preprocess a source file
src/remesh.cpp.i:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/remesh.cpp.i
.PHONY : src/remesh.cpp.i

src/remesh.s: src/remesh.cpp.s

.PHONY : src/remesh.s

# target to generate assembly for a file
src/remesh.cpp.s:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/src/remesh.cpp.s
.PHONY : src/remesh.cpp.s

util/Properties.o: util/Properties.cpp.o

.PHONY : util/Properties.o

# target to build an object file
util/Properties.cpp.o:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/util/Properties.cpp.o
.PHONY : util/Properties.cpp.o

util/Properties.i: util/Properties.cpp.i

.PHONY : util/Properties.i

# target to preprocess a source file
util/Properties.cpp.i:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/util/Properties.cpp.i
.PHONY : util/Properties.cpp.i

util/Properties.s: util/Properties.cpp.s

.PHONY : util/Properties.s

# target to generate assembly for a file
util/Properties.cpp.s:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/util/Properties.cpp.s
.PHONY : util/Properties.cpp.s

util/util.o: util/util.cpp.o

.PHONY : util/util.o

# target to build an object file
util/util.cpp.o:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/util/util.cpp.o
.PHONY : util/util.cpp.o

util/util.i: util/util.cpp.i

.PHONY : util/util.i

# target to preprocess a source file
util/util.cpp.i:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/util/util.cpp.i
.PHONY : util/util.cpp.i

util/util.s: util/util.cpp.s

.PHONY : util/util.s

# target to generate assembly for a file
util/util.cpp.s:
	$(MAKE) -f CMakeFiles/project_bin.dir/build.make CMakeFiles/project_bin.dir/util/util.cpp.s
.PHONY : util/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... project_bin"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... igl_viewer"
	@echo "... igl_opengl_glfw"
	@echo "... igl_opengl2"
	@echo "... igl_opengl"
	@echo "... igl"
	@echo "... nanogui"
	@echo "... nanogui-obj"
	@echo "... glfw_objects"
	@echo "... glfw"
	@echo "... Detector/HarrisDetector.o"
	@echo "... Detector/HarrisDetector.i"
	@echo "... Detector/HarrisDetector.s"
	@echo "... Detector/Mesh.o"
	@echo "... Detector/Mesh.i"
	@echo "... Detector/Mesh.s"
	@echo "... Detector/Vertex.o"
	@echo "... Detector/Vertex.i"
	@echo "... Detector/Vertex.s"
	@echo "... src/Process.o"
	@echo "... src/Process.i"
	@echo "... src/Process.s"
	@echo "... src/funcgui.o"
	@echo "... src/funcgui.i"
	@echo "... src/funcgui.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/myDisplay.o"
	@echo "... src/myDisplay.i"
	@echo "... src/myDisplay.s"
	@echo "... src/mySkeleton.o"
	@echo "... src/mySkeleton.i"
	@echo "... src/mySkeleton.s"
	@echo "... src/remesh.o"
	@echo "... src/remesh.i"
	@echo "... src/remesh.s"
	@echo "... util/Properties.o"
	@echo "... util/Properties.i"
	@echo "... util/Properties.s"
	@echo "... util/util.o"
	@echo "... util/util.i"
	@echo "... util/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

